// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type QunuxSnapshotNotification = {
/**
 * Codex thread that should receive and render this snapshot.
 */
threadId: string,
/**
 * Stable Qunux process identity for the current Codex session.
 */
processId: string,
/**
 * Qunux logical thread that produced or owns the snapshot.
 */
qunuxThreadId: string,
/**
 * Optional persisted snapshot path for debug/offline fallback.
 */
statePath: string | null,
/**
 * Runtime snapshot payload. Currently mirrors the persisted Qunux closure state.
 */
snapshot: JsonValue, };
